"""SE(3) utilities and the naming convention used throughout this repository.

SE(3) -- the Special Euclidean group in 3 dimensions -- is the set of rigid
body motions: rotation plus translation, no scaling and no reflection. An
element is represented as a 4x4 homogeneous matrix::

    T = [ R  p ]     R in SO(3), a 3x3 rotation
        [ 0  1 ]     p in R^3,   a translation

The trailing ``[0 0 0 1]`` row exists so that composition is ordinary matrix
multiplication.

Naming convention
-----------------
``T_a_b`` means "the pose of frame b expressed in frame a", equivalently "the
transform that takes coordinates written in b and returns them written in a".
Adjacent subscripts cancel under composition::

    T_a_b @ T_b_c == T_a_c

If the inner indices of a product do not match, the expression is a bug. Most
robotics defects are frame defects, and this convention turns a whole class of
them into something you can spot by reading.
"""

from __future__ import annotations

import numpy as np

__all__ = [
    "compose",
    "identity",
    "inverse",
    "rotation_of",
    "rot_x",
    "rot_y",
    "rot_z",
    "se3",
    "transform_point",
    "translation_of",
    "wrap_to_pi",
]


def identity() -> np.ndarray:
    """The identity transform: do not move."""
    return np.eye(4)


def se3(rotation: np.ndarray, translation: np.ndarray) -> np.ndarray:
    """Assemble a 4x4 homogeneous transform from a 3x3 rotation and a 3-vector."""
    rotation = np.asarray(rotation, dtype=float)
    translation = np.asarray(translation, dtype=float)
    if rotation.shape != (3, 3):
        raise ValueError(f"rotation must be 3x3, got {rotation.shape}")
    if translation.shape != (3,):
        raise ValueError(f"translation must be a 3-vector, got {translation.shape}")

    transform = np.eye(4)
    transform[:3, :3] = rotation
    transform[:3, 3] = translation
    return transform


def rot_x(angle_rad: float) -> np.ndarray:
    """Rotation about the x axis, right-handed."""
    c, s = np.cos(angle_rad), np.sin(angle_rad)
    return np.array([[1.0, 0.0, 0.0], [0.0, c, -s], [0.0, s, c]])


def rot_y(angle_rad: float) -> np.ndarray:
    """Rotation about the y axis, right-handed."""
    c, s = np.cos(angle_rad), np.sin(angle_rad)
    return np.array([[c, 0.0, s], [0.0, 1.0, 0.0], [-s, 0.0, c]])


def rot_z(angle_rad: float) -> np.ndarray:
    """Rotation about the z axis, right-handed."""
    c, s = np.cos(angle_rad), np.sin(angle_rad)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def rotation_of(transform: np.ndarray) -> np.ndarray:
    """Extract the 3x3 rotation block."""
    return np.asarray(transform)[:3, :3]


def translation_of(transform: np.ndarray) -> np.ndarray:
    """Extract the 3-vector translation block."""
    return np.asarray(transform)[:3, 3]


def inverse(transform: np.ndarray) -> np.ndarray:
    """Invert a homogeneous transform.

    Uses the rigid-body structure rather than a general matrix inverse: for
    ``T = [R p; 0 1]`` the inverse is ``[R^T  -R^T p; 0 1]``. This is both
    faster and numerically better behaved than ``np.linalg.inv``.
    """
    transform = np.asarray(transform, dtype=float)
    rotation = transform[:3, :3]
    translation = transform[:3, 3]
    return se3(rotation.T, -rotation.T @ translation)


def compose(*transforms: np.ndarray) -> np.ndarray:
    """Chain transforms left to right: ``compose(T_a_b, T_b_c) -> T_a_c``."""
    result = np.eye(4)
    for transform in transforms:
        result = result @ np.asarray(transform, dtype=float)
    return result


def transform_point(transform: np.ndarray, point: np.ndarray) -> np.ndarray:
    """Apply ``T_a_b`` to a point written in frame b, returning it in frame a."""
    point = np.asarray(point, dtype=float)
    homogeneous = np.append(point, 1.0)
    return (np.asarray(transform, dtype=float) @ homogeneous)[:3]


def wrap_to_pi(angle_rad: float | np.ndarray) -> np.ndarray:
    """Wrap an angle into ``(-pi, pi]``.

    Needed wherever a solution family is generated by adding pi (the shoulder
    flip in inverse kinematics, for instance), so that the result can be
    compared against joint limits meaningfully.
    """
    return (np.asarray(angle_rad) + np.pi) % (2.0 * np.pi) - np.pi
