"""Generate URDF and MJCF descriptions from ``config/arm.toml``.

Neither file is ever hand-edited. They are derived artefacts, regenerated by
``just models`` and committed so that a change to the parameters shows up as a
reviewable diff ("link 2 grew 30 mm") rather than as invisible drift. A test
asserts that regenerating produces no diff, which catches hand edits.

Why two formats:

* **URDF** is the interchange format. Pinocchio, MuJoCo, Rerun and the whole
  ROS ecosystem read it. It describes the kinematic tree, joint origins and
  axes, limits, and link inertials.
* **MJCF** is MuJoCo's native format. It carries everything URDF does plus the
  things URDF has no vocabulary for: actuators, sensors, solver settings and
  the scene itself.

URDF can only describe *trees*. Closed loops -- four-bar linkages, parallel
mechanisms, belt coupling between joints -- cannot be expressed. Irrelevant for
this arm, but the reason MJCF exists alongside it.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path
from xml.dom import minidom

from arm.params import REPO_ROOT, ArmParams, default_params

GENERATED_DIR = REPO_ROOT / "models" / "generated"
MESH_DIR = REPO_ROOT / "cad" / "export"
# Path from models/generated/ to cad/export/, as written into the model files.
MESH_RELATIVE = "../../cad/export"
URDF_PATH = GENERATED_DIR / "arm.urdf"
MJCF_PATH = GENERATED_DIR / "arm.xml"

_BANNER = (
    " GENERATED FILE -- DO NOT EDIT.\n"
    "     Source:    config/arm.toml\n"
    "     Generator: src/arm/models.py  (run `just models`)\n"
    "     Edits here are silently discarded on the next regeneration. "
)

# Collision geometry. These mirror the printed cross-section in cad/links.py;
# tests/test_cad.py asserts they stay in step, because models.py cannot import
# from cad/ (build123d is not in the default shell).
#
# Boxes rather than capsules, deliberately. A capsule has hemispherical caps, so
# one running from z=0 upwards extends a full radius *below* its start -- the
# base capsule sat 15 mm inside the floor and MuJoCo resolved a contact
# constraint on every step of every simulation. A box matches a rectangular
# printed beam anyway; the 15 mm capsule radius was simultaneously wider than
# the part is tall and narrower than it is wide.
SECTION_WIDTH_M = 0.030
SECTION_HEIGHT_M = 0.022
_LINK_THICKNESS_M = SECTION_WIDTH_M
LINK_RADIUS_M = SECTION_HEIGHT_M / 2.0


def _collision_box(length: float, along: str):
    """Half-extents and centre of a link's collision box, in its own frame.

    Sized to the printed section and centred on the link, so it never reaches
    past the joint at either end -- which is what made the previous capsules
    intersect the floor and each other.
    """
    if along == "z":
        return (
            (SECTION_WIDTH_M / 2, SECTION_WIDTH_M / 2, length / 2),
            (0.0, 0.0, length / 2),
        )
    return (
        (length / 2, SECTION_WIDTH_M / 2, SECTION_HEIGHT_M / 2),
        (length / 2, 0.0, 0.0),
    )


def _meshes_available() -> bool:
    """Whether the CAD exports exist.

    Generation must not require the CAD shell -- `just models` runs in the
    default environment. When the meshes are absent the models fall back to
    capsules, which is exactly what they were before the CAD existed.
    """
    return all((MESH_DIR / f"{name}.stl").exists() for name in ("base", "upper_arm", "forearm"))


def _fmt(value: float) -> str:
    """Fixed formatting so regeneration is byte-stable."""
    return f"{value:.9g}"


def _vec(values) -> str:
    return " ".join(_fmt(v) for v in values)


def _pretty(root: ET.Element, banner: str) -> str:
    raw = ET.tostring(root, encoding="unicode")
    parsed = minidom.parseString(raw)
    body = parsed.documentElement.toprettyxml(indent="  ")
    return f'<?xml version="1.0"?>\n<!--{banner}-->\n{body}'


def _chain(params: ArmParams):
    """The arm as (joint, child_link, origin, link_length) tuples.

    Encodes the Level-1 shorthand described in docs/03-kinematics.md: every
    joint-to-joint transform here is a pure translation along a single axis,
    which is why ``[geometry]`` needs only three scalars. A wrist or a link
    offset would force per-joint origins instead.
    """
    length_base, length_upper, length_fore = params.link_lengths_m
    joint_base, joint_shoulder, joint_elbow = params.joints
    link_base, link_upper, link_fore = params.links

    return [
        (joint_base, link_base, (0.0, 0.0, 0.0), length_base, "z"),
        (joint_shoulder, link_upper, (0.0, 0.0, length_base), length_upper, "x"),
        (joint_elbow, link_fore, (length_upper, 0.0, 0.0), length_fore, "x"),
    ]


# ---------------------------------------------------------------------------
# URDF
# ---------------------------------------------------------------------------


def build_urdf(params: ArmParams | None = None) -> str:
    params = params or default_params()
    robot = ET.Element("robot", name=params.meta.name)

    # A massless root. Pinocchio treats this as the fixed world attachment.
    ET.SubElement(robot, "link", name="world")

    _, _, length_fore = params.link_lengths_m
    previous = "world"

    for joint, link, origin, length, along in _chain(params):
        actuator = params.actuators[joint.actuator]

        element = ET.SubElement(robot, "joint", name=joint.name, type="revolute")
        ET.SubElement(element, "parent", link=previous)
        ET.SubElement(element, "child", link=link.name)
        ET.SubElement(element, "origin", xyz=_vec(origin), rpy="0 0 0")
        ET.SubElement(element, "axis", xyz=_vec(joint.axis))
        ET.SubElement(
            element,
            "limit",
            lower=_fmt(joint.limit_lower_rad),
            upper=_fmt(joint.limit_upper_rad),
            effort=_fmt(actuator.continuous_torque_nm),
            velocity=_fmt(actuator.no_load_speed_rads),
        )

        _urdf_link(robot, link, length, along)
        previous = link.name

    # An explicit end-effector frame. Pinocchio resolves poses by frame name,
    # so the point our fk() computes must exist here to be comparable.
    tip = ET.SubElement(robot, "joint", name="ee_fixed", type="fixed")
    ET.SubElement(tip, "parent", link=previous)
    ET.SubElement(tip, "child", link="ee")
    ET.SubElement(tip, "origin", xyz=_vec((length_fore, 0.0, 0.0)), rpy="0 0 0")
    ET.SubElement(robot, "link", name="ee")

    return _pretty(robot, _BANNER)


def _urdf_link(robot: ET.Element, link, length: float, along: str) -> None:
    element = ET.SubElement(robot, "link", name=link.name)

    inertial = ET.SubElement(element, "inertial")
    ET.SubElement(inertial, "origin", xyz=_vec(link.com_m), rpy="0 0 0")
    ET.SubElement(inertial, "mass", value=_fmt(link.mass_kg))
    ixx, iyy, izz = link.inertia_kgm2
    ET.SubElement(
        inertial,
        "inertia",
        ixx=_fmt(ixx),
        ixy="0",
        ixz="0",
        iyy=_fmt(iyy),
        iyz="0",
        izz=_fmt(izz),
    )

    half, centre = _collision_box(length, along)
    size = tuple(2.0 * h for h in half)

    visual = ET.SubElement(element, "visual")
    if _meshes_available():
        ET.SubElement(visual, "origin", xyz="0 0 0", rpy="0 0 0")
        geometry = ET.SubElement(visual, "geometry")
        ET.SubElement(geometry, "mesh", filename=f"{MESH_RELATIVE}/{link.name}.stl")
    else:
        ET.SubElement(visual, "origin", xyz=_vec(centre), rpy="0 0 0")
        geometry = ET.SubElement(visual, "geometry")
        ET.SubElement(geometry, "box", size=_vec(size))

    collision = ET.SubElement(element, "collision")
    ET.SubElement(collision, "origin", xyz=_vec(centre), rpy="0 0 0")
    geometry = ET.SubElement(collision, "geometry")
    ET.SubElement(geometry, "box", size=_vec(size))


# ---------------------------------------------------------------------------
# MJCF
# ---------------------------------------------------------------------------


def build_mjcf(params: ArmParams | None = None, *, meshdir: str | None = None) -> str:
    """Generate MJCF. ``meshdir`` defaults to the path relative to the written file.

    A model compiled from a *string* has no file to be relative to, so
    MuJoCo cannot resolve ``../../cad/export``. Callers that compile in memory
    (``MujocoArm(from_params=True)``) must pass an absolute path instead.
    """
    params = params or default_params()
    root = ET.Element("mujoco", model=params.meta.name)

    ET.SubElement(root, "compiler", angle="radian", meshdir=meshdir or MESH_RELATIVE)

    # Visual meshes exported from the CAD. Collision stays on the capsules
    # below: convexified meshes are slower and buy nothing for an arm whose
    # links are convex-ish anyway. Separating visual from collision geometry is
    # standard practice, not a shortcut.
    if _meshes_available():
        assets = ET.SubElement(root, "asset")
        for _, link, _, _, _ in _chain(params):
            ET.SubElement(assets, "mesh", name=f"{link.name}_mesh", file=f"{link.name}.stl")
    ET.SubElement(
        root,
        "option",
        timestep=_fmt(params.sim.timestep_s),
        gravity=_vec(params.sim.gravity_ms2),
        integrator="implicitfast",
    )

    defaults = ET.SubElement(root, "default")
    ET.SubElement(defaults, "geom", rgba="0.5 0.6 0.7 1", contype="1", conaffinity="1")
    # No default joint block: armature and damping are per-actuator and are
    # written onto each joint from config/arm.toml.

    worldbody = ET.SubElement(root, "worldbody")
    ET.SubElement(worldbody, "light", pos="0 0 1.5", dir="0 0 -1", diffuse="0.8 0.8 0.8")
    ET.SubElement(
        worldbody,
        "geom",
        name="floor",
        type="plane",
        size="1 1 0.05",
        rgba="0.25 0.26 0.28 1",
    )

    # Static obstacles, welded to the world. Collision geometry only: they carry
    # no mass and are never simulated as dynamic bodies, because their only job
    # is to be something the planner has to route around.
    for obstacle in params.obstacles:
        ET.SubElement(
            worldbody,
            "geom",
            name=f"obstacle_{obstacle.name}",
            type="box",
            pos=_vec(obstacle.pos_m),
            size=_vec(obstacle.half_size_m),
            rgba="0.45 0.35 0.30 1",
        )

    _, _, length_fore = params.link_lengths_m
    parent = worldbody

    for joint, link, origin, length, along in _chain(params):
        actuator = params.actuators[joint.actuator]
        body = ET.SubElement(parent, "body", name=link.name, pos=_vec(origin))
        # armature and damping come from the actuator, never from a hard-coded
        # default: the controller's model reads the same numbers out of the same
        # TOML, and a value only one engine knows about silently makes them
        # different robots.
        ET.SubElement(
            body,
            "joint",
            name=joint.name,
            type="hinge",
            axis=_vec(joint.axis),
            range=f"{_fmt(joint.limit_lower_rad)} {_fmt(joint.limit_upper_rad)}",
            armature=_fmt(actuator.armature_kgm2),
            damping=_fmt(actuator.damping_nms_rad),
            frictionloss=_fmt(actuator.coulomb_friction_nm),
        )
        ixx, iyy, izz = link.inertia_kgm2
        ET.SubElement(
            body,
            "inertial",
            pos=_vec(link.com_m),
            mass=_fmt(link.mass_kg),
            diaginertia=f"{_fmt(ixx)} {_fmt(iyy)} {_fmt(izz)}",
        )

        half, centre = _collision_box(length, along)
        ET.SubElement(
            body,
            "geom",
            name=f"{link.name}_collision",
            type="box",
            pos=_vec(centre),
            size=_vec(half),
            group="3",
            rgba="0.8 0.3 0.3 0.25",
        )
        if _meshes_available():
            ET.SubElement(
                body,
                "geom",
                name=f"{link.name}_visual",
                type="mesh",
                mesh=f"{link.name}_mesh",
                contype="0",
                conaffinity="0",
                group="2",
                rgba="0.62 0.66 0.72 1",
            )
        parent = body

    # Matches the URDF's ee frame so both models measure the same point.
    ET.SubElement(parent, "site", name="ee", pos=_vec((length_fore, 0.0, 0.0)), size="0.006")

    # Actuators: the thing URDF has no vocabulary for. Torque control, because
    # that is the point of choosing servos with a current-control mode.
    actuators = ET.SubElement(root, "actuator")
    for joint, *_ in _chain(params):
        limit = params.actuators[joint.actuator].continuous_torque_nm
        ET.SubElement(
            actuators,
            "motor",
            name=f"{joint.name}_motor",
            joint=joint.name,
            ctrlrange=f"{_fmt(-limit)} {_fmt(limit)}",
            gear="1",
        )

    # The pedestal is bolted to the surface it stands on, and its only freedom
    # is rotation about z -- so contact between it and the floor can never do
    # anything except cost solver time. Its bottom face sits exactly on the
    # floor plane, which produced four coincident-surface contacts on every
    # step of every simulation.
    contacts = ET.SubElement(root, "contact")
    base_link = _chain(params)[0][1]
    ET.SubElement(contacts, "exclude", body1="world", body2=base_link.name)

    sensors = ET.SubElement(root, "sensor")
    for joint, *_ in _chain(params):
        ET.SubElement(sensors, "jointpos", name=f"{joint.name}_pos", joint=joint.name)
        ET.SubElement(sensors, "jointvel", name=f"{joint.name}_vel", joint=joint.name)
    ET.SubElement(sensors, "framepos", name="ee_pos", objtype="site", objname="ee")

    return _pretty(root, _BANNER)


def write_models(params: ArmParams | None = None, directory: Path | None = None):
    """Write both descriptions; returns the paths written."""
    directory = directory or GENERATED_DIR
    directory.mkdir(parents=True, exist_ok=True)

    urdf = directory / "arm.urdf"
    mjcf = directory / "arm.xml"
    urdf.write_text(build_urdf(params))
    mjcf.write_text(build_mjcf(params))
    return urdf, mjcf
